seed_everything: null
trainer:
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: epe_val
        mode: min
        save_top_k: 5
        save_last: true
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      save_dir: ./logs
      project: lightning-raft
      name: debug
  default_root_dir: null
  gradient_clip_val: 1.0
  gradient_clip_algorithm: norm
  gpus: 1
  fast_dev_run: false
  max_epochs: 5
  max_steps: 100000
  limit_train_batches: 5
  limit_val_batches: 5
  val_check_interval: 1.0
  log_every_n_steps: 50
  accelerator: null
  precision: 32
  num_sanity_val_steps: 0
model:
  hidden_dim: 128
  context_dim: 128
  corr_levels: 4
  corr_radius: 4
  iters: 12
  gamma: 0.8
  dropout: 0.0
  lr: 0.0004
  wdecay: 0.0001
  epsilon: 1.0e-08
data:
  stage: chairs
  image_size:
  - 368 
  - 496
  batch_size: 4
  num_workers: 4
  root_chairs: datasets/FlyingChairs/data
  root_things: datasets/FlyingThings3D
  root_sintel: datasets/Sintel
  root_kitti: datasets/KITTI
  root_hd1k: datasets/HD1k
name: raft-chairs
restore_ckpt: null
validation: null
