seed_everything: null
trainer:
  logger: true
  checkpoint_callback: true
  callbacks: null
  default_root_dir: null
  gradient_clip_val: 1.0
  gradient_clip_algorithm: norm
  process_position: 0
  num_nodes: 1
  num_processes: 1
  gpus: 1
  auto_select_gpus: false
  tpu_cores: null
  ipus: null
  log_gpu_memory: null
  progress_bar_refresh_rate: null
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1
  fast_dev_run: false
  accumulate_grad_batches: 1
  max_epochs: null
  min_epochs: null
  max_steps: 100000
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0
  flush_logs_every_n_steps: 100
  log_every_n_steps: 50
  accelerator: null
  sync_batchnorm: false
  precision: 32
  weights_summary: top
  weights_save_path: null
  num_sanity_val_steps: 0
  truncated_bptt_steps: null
  resume_from_checkpoint: null
  profiler: null
  benchmark: false
  deterministic: false
  reload_dataloaders_every_n_epochs: 0
  reload_dataloaders_every_epoch: false
  auto_lr_find: false
  replace_sampler_ddp: true
  terminate_on_nan: false
  auto_scale_batch_size: false
  prepare_data_per_node: true
  plugins: null
  amp_backend: native
  amp_level: O2
  distributed_backend: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  stochastic_weight_avg: false
model:
  hidden_dim: 128
  context_dim: 128
  corr_levels: 4
  corr_radius: 4
  iters: 12
  gamma: 0.8
  dropout: 0.0
  lr: 0.0004
  wdecay: 0.0001
  epsilon: 1.0e-08
data:
  stage: chairs
  image_size:
  - 368 
  - 496
  batch_size: 4
  num_workers: 4
  root_chairs: datasets/FlyingChairs/data
  root_things: datasets/FlyingThings3D
  root_sintel: datasets/Sintel
  root_kitti: datasets/KITTI
  root_hd1k: datasets/HD1k
name: raft-chairs
restore_ckpt: null
validation: null
