seed_everything: 1234

trainer:
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: epe_val
        mode: min
        save_top_k: -1
        save_last: true
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
  gradient_clip_val: 1.0
  gradient_clip_algorithm: norm
  gpus: 1
  val_check_interval: 1.0
  num_sanity_val_steps: 0
  log_every_n_steps: 50
  precision: 16

data:
  num_workers: 8
  root_chairs: datasets/FlyingChairs/data
  root_things: datasets/FlyingThings3D
  root_sintel: datasets/MPI-Sintel
  root_kitti: datasets/KITTI-Flow-2015
  root_hd1k: datasets/HD1K
