restore_weights: pretrained/checkpoints/raft-things.ckpt

trainer:
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      save_dir: ./logs
      project: lightning-raft
      name: raft-sintel
  max_steps: 120000

model:
  hidden_dim: 128
  context_dim: 128
  corr_levels: 4
  corr_radius: 4
  iters: 12
  iters_val: 32
  gamma: 0.85
  dropout: 0.0
  lr: 0.0001
  wdecay: 0.00001
  epsilon: 1.0e-08

data:
  stage: sintel
  image_size:
  - 368
  - 768
  batch_size: 5
