restore_weights: pretrained/checkpoints/raft-chairs.ckpt

trainer:
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      save_dir: ./logs
      project: lightning-raft
      name: raft-things
  max_steps: 120000

model:
  hidden_dim: 128
  context_dim: 128
  corr_levels: 4
  corr_radius: 4
  iters: 12
  iters_val: 32
  gamma: 0.8
  dropout: 0.0
  lr: 0.0001
  wdecay: 0.0001
  epsilon: 1.0e-08

data:
  stage: things
  image_size:
  - 400
  - 720
  batch_size: 5
